name: DMP 2024 Project Template
description: List a new project for Dedicated Mentoring Program (DMP) 2024 
title: "[DMP 2024]: "
labels: ["DMP 2024"]
body:
  - type: textarea
    id: ticket-description
    validations:
      required: true
    attributes:
      label: Ticket Contents
      value: |
        ## Description
        [Belongg is developing BelonggAI, a tool that will help development practitioners, researchers, funders, etc analyze their proposals, program documents, policy documents, etc to discover intersectional perspectives (gender, disability, sexual orientation,  caste, religion, etc) that could get added to make the program more inclusive. The tool is based on a RAG architecture, with customized prompts, and a corpus running into thousands of research papers, media articles, grey literature. This is constantly growing as we expand our focus areas. However, all of this is still in English. 
        To avoid omitting the knowledge produced by and on marginalized and underserved communities, we are committed to building on the tool’s capability to process knowledge produced in languages other than English.  To this end, Belongg would like to undertake a project to develop a tool to translate text documents, audio, and videos in Indian languages to PDFs with English text. The developed tool will be embedded in our existing LLM model that can only process English text. While working on this project, the intern selected as part of DMP  will receive guidance from a Belongg mentor to coordinate with our technology team (which includes an LLM engineer and colleagues from ARTPark)  and receive mentorship from a separate mentor assigned by Samagra to provide technical assistance to the intern]

  - type: textarea
    id: ticket-goals
    validations:
      required: true
    attributes:
      label: Goals & Mid-Point Milestone
      description: List the goals of the feature. Please add the goals that must be achieved by Mid-point check-in i.e 1.5 months into the coding period.
      value: |
        ## Goals
        - [ ] [User-Friendly Input Interface]
        - [ ] [Batch Processing and Metadata Management]
        - [ ] [Translation and Conversion to English Text]
        - [ ] [Integration with Google Drive and Sheets]
        - [ ] [Goals Achieved By Mid-point Milestone]

  - type: textarea
    id: ticket-setup
    attributes:
      label: Setup/Installation 
      description: Please list or link setup or installation guide (if any)

  - type: textarea
    id: ticket-expected-outcome
    attributes:
      label: Expected Outcome
      description: 
      1. Development of Multilingual Translation Tool:
      Objective: Design and implement a comprehensive tool (likely built using Bhaashini) capable of translating text, audio, and video content from multiple Indian languages into English text, ensuring seamless integration with the existing LLM framework.
      Specifications: The tool should leverage advanced language translation technologies to ensure high fidelity and accuracy and should work with a large number of major and minor Indian languages (those supported by efforts such as Bhashini).
      2. Quality Assurance and Performance Metrics:
      Objective: Establish a process to measure and benchmark translation quality, speed, and reliability, ensuring the tool meets the specific needs of BelonggAI’s knowledge repository.
      Specifications: Implement a testing framework to evaluate the translation accuracy, the integrity of metadata, and the processing speed. Define clear performance metrics, such as a specific accuracy rate in translations and a maximum processing time of time for different types of content. We will be able to provide fees to cover license fees to cover any additional SaaS tools or LLM performance measurement tools for this (such as Uptrain). 
      3. Integration and Usability:
      Objective: Ensure the translation tool is fully compatible and is able to ingest input files and deliver the output files using the existing BelonggAI data storage protocols and folder structures (Google Drive folders with API access) and streamline the process of updating the knowledge repository for both the technology team and the model itself.
      Specifications: The tool must feature a user-friendly interface for manual operations and support automated batch processing for large datasets. It should automatically tag and store translated documents with relevant metadata in a designated Google Drive, adhering to predefined organizational standards.
      4. Documentation and Training Materials:
      Objective: Provide comprehensive documentation and training resources to ensure sustainable use and maintenance of the translation tool by Belongg’s team.
      Specifications: Develop detailed user manuals, technical documentation, and video tutorials covering tool usage, troubleshooting, and best practices for content translation and management.
      5. Progress Reporting and Feedback Mechanism:
      Objective: Establish a structured reporting and feedback loop to monitor the project's progress, address challenges, and incorporate stakeholder feedback.
      Specifications: The intern will submit bi-weekly progress reports outlining achievements, encountered issues, and next steps. A monthly review meeting with the mentorship team and relevant stakeholders will be held to discuss progress and adjust project direction as needed.

  - type: textarea
    id: ticket-acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: 
      1. Functionality of the Input Interface: The webpage must be secure, user-friendly, and capable of handling multiple file uploads with associated metadata. Only authorized Belongg team members should access this portal.
      2. Accuracy and Reliability of Translation: The system must deliver high-quality translations with a predefined accuracy threshold (e.g., 95% accuracy), ensuring the content is contextually and culturally accurate in English.
      3. Efficient Batch Processing: The tool should handle batch uploads seamlessly, with each files metadata accurately captured and associated with the corresponding translated content in the output.
      4. Seamless Integration and Data Management: Successful integration with Google Drive for storing translated files and Google Sheets for real-time status updates. The system should maintain a high level of organization, allowing easy retrieval and tracking of processed knowledge assets

  - type: textarea
    id: ticket-implementation-details
    validations:
      required: true
    attributes:
      label: Implementation Details
      description: 
      1. Webpage Development: The webpage will be developed using web development technologies with backend support for user authentication (e.g., OAuth for username/password login). This ensures a secure and accessible platform for file submission.
      2. Translation and Text Conversion Technology: Utilizing advanced AI and machine learning technologies for language translation and speech-to-text conversion. This includes leveraging open-source libraries and possibly integrating with third-party APIs to support a wide range of languages and content formats.
      3. Batch Processing and Metadata Handling: Implementation of a backend system capable of processing multiple uploads simultaneously, extracting metadata for each file, and ensuring each piece of content is appropriately tagged and stored.
      4. Google Drive and Sheets API Integration: Using Google Drive API for storing translated documents and Google Sheets API for updating the tracking spreadsheet. This requires careful planning to ensure data consistency, access management, and real-time update capabilities.
      5. Continuous Monitoring and Feedback Loop: Setting up mechanisms for monitoring the system's performance, gathering user feedback, and making iterative improvements to enhance functionality, user experience, and translation accuracy.

  - type: textarea
    id: ticket-mockups
    attributes:
      label: Mockups/Wireframes
      description: Include links to any visual aids, mockups, wireframes, or diagrams that help illustrate what the final product should look like. This is not always necessary, but can be very helpful in many cases.

  - type: input
    id: ticket-product
    attributes:
      label: Product Name
      placeholder: Enter Product Name
    validations:
      required: true

  - type: dropdown
    id: ticket-organisation
    attributes:
      label: Organisation Name
      description: Enter Organisation Name
      multiple: false
      options:
        - Bandhu
        - Blockster Global (CREDBEL)
        - Civis
        - Dhwani
        - Dhiway
        - EGov
        - EkShop Marketplace
        - FIDE
        - If Me
        - Key Education Foundation
        - Norwegian Meteorological Institute
        - Planet Read
        - Project Second Chance
        - Reap Benefit
        - SamagraX
        - ShikshaLokam
        - Tech4Dev
        - Tekdi
        - The Mifos Initiative
        - Tibil
        - Ushahidi
        - Arghyam
        - Piramal Swasthya Management Research Institute
    validations:
      required: true

  - type: dropdown
    id: ticket-governance-domain
    attributes:
      label: Domain
      options:
        - ⁠Healthcare 
        - ⁠Education
        - Financial Inclusion
        - ⁠Livelihoods
        - ⁠Skilling 
        - ⁠Learning & Development
        - ⁠Agriculture
        - ⁠Service Delivery
        - Open Source Library
        - Water
    validations:
      required: true


  - type: dropdown
    id: ticket-technical-skills-required
    attributes:
      label: Tech Skills Needed
      description: Select the technologies needed for this ticket (use Ctrl or Command to select multiple)
      multiple: true
      options:
        - .NET
        - Angular
        - Artificial Intelligence
        - ASP.NET
        - AWS
        - Babel
        - Bootstrap
        - C#
        - Chart.js
        - CI/CD
        - Computer Vision
        - CORS
        - cURL
        - Cypress
        - D3.js
        - Database
        - Debugging
        - Design
        - DevOps
        - Django
        - Docker
        - Electron
        - ESLint
        - Express.js
        - Feature
        - Flask
        - Go
        - GraphQL
        - HTML
        - Ionic
        - Jest
        - Java
        - JavaScript
        - Jenkins
        - JWT
        - Kubernetes
        - Laravel
        - Machine Learning
        - Maintenance
        - Markdown
        - Material-UI
        - Microservices
        - MongoDB
        - Mobile
        - Mockups
        - Mocha
        - Natural Language Processing
        - NestJS
        - Node.js
        - NUnit
        - OAuth
        - Performance Improvement
        - Prettier
        - Python
        - Question
        - React
        - React Native
        - Redux
        - RESTful APIs
        - Ruby
        - Ruby on Rails
        - Rust
        - Scala
        - Security
        - Selenium
        - SEO
        - Serverless
        - Solidity
        - Spring Boot
        - SQL
        - Swagger
        - Tailwind CSS
        - Test
        - Testing Library
        - Three.js
        - TypeScript
        - UI/UX/Design
        - Virtual Reality
        - Vue.js
        - WebSockets
        - Webpack
        - Other
    validations:
      required: true

  - type: textarea
    id: ticket-mentors
    attributes:
      label: Mentor(s)
      description: Please tag relevant mentors for the ticket
    validations:
      required: true

  - type: dropdown
    id: ticket-category
    attributes: 
      label: Category
      description: Choose the categories that best describe your ticket
      multiple: true
      options:
        - API
        - Analytics
        - Accessibility
        - Backend
        - Breaking Change
        - Beginner Friendly
        - Configuration
        - CI/CD
        - Database
        - Data Science
        - Deprecation
        - Documentation
        - Delpoyment
        - Frontend
        - Internationalization
        - Localization
        - Machine Learning
        - Maintenance
        - Mobile
        - Performance Improvement
        - Question
        - Refactoring
        - Research
        - Needs Reproduction
        - SEO
        - Security
        - Testing
        - AI
        - Other
    validations:
      required: true

  
